/* Clip-E dashboard refresh v2 */
import React,{useState} from'react';import{createRoot}from'react-dom/client';import{Camera,Upload,ArrowRight,ShieldCheck,Wifi,CheckCircle2,Scissors,Sparkles,Target,Activity,ChevronRight,Mic,Pause,Square,Volume2,Eye,Accessibility,RotateCcw,MessageCircle}from'lucide-react';import'./styles.css';

const steps=['Discover','Scan','Analyze','Select','Customize','Map','Safety','Live Cut','Journey','Accessibility'];
const styles=[['Precision Taper','Clean structure with controlled graduation.'],['Textured Crop','Shape-forward texture with manageable length.'],['Classic Short','Balanced proportions and consistent maintenance.']];
const zones=[['Top','12 mm','4 mm'],['Sides','9 mm','6 mm'],['Back','9 mm','5 mm'],['Neckline','6 mm','3 mm']];

function ConceptHead({view='front',hair='crop',technical=false,active=false,className=''}){return <div className={'conceptHead '+view+' '+hair+' '+(technical?'technical ':'')+(active?'active ':'')+className}><div className="cranium"/><div className="ear earL"/><div className="ear earR"/><div className="facePlane"><i className="brow browL"/><i className="brow browR"/><i className="eye eyeL"/><i className="eye eyeR"/><i className="nose"/><i className="mouth"/><i className="jaw"/></div><div className="neck"/><div className="hairMass"><i/><i/><i/><i/><i/><i/><i/></div><div className="fade fadeL"/><div className="fade fadeR"/>{technical&&<><div className="contour c1"/><div className="contour c2"/><div className="contour c3"/><span className="scanPoint sp1"/><span className="scanPoint sp2"/><span className="scanPoint sp3"/></>}{active&&<div className="cutHeat"/>}</div>}
function Arm({mode='home'}){return <div className={'arm '+mode} aria-label="Clip-E robotic arm visualization"><div className="base"/><div className="joint j1"/><div className="link l1"/><div className="joint j2"/><div className="link l2"/><div className="joint j3"/><div className="tool"><Scissors size={18}/></div><div className="path"/></div>}
function Header({step,setStep}){return <><header><button className="brand" onClick={()=>setStep(0)}><span className="mark">C</span><span>THE CLIP LAB<small>POWERED BY CLIP-E</small></span></button><nav>{steps.map((s,i)=><button className={step===i?'active':''} onClick={()=>setStep(i)} key={s}>{s}</button>)}</nav><span className="status"><i/> SYSTEM ONLINE</span></header><div className="progress"><span style={{width:(step/(steps.length-1)*100)+'%'}}/></div></>}
function Shell({step,setStep,children,title,kicker,desc}){return <main><div className="eyebrow">{kicker}</div><h1>{title}</h1>{desc&&<p className="lead">{desc}</p>}{children}<div className="pager">{step>0&&<button className="ghost" onClick={()=>setStep(step-1)}>Back</button>}{step<9&&<button className="primary" onClick={()=>setStep(step+1)}>Continue <ArrowRight size={17}/></button>}</div></main>}

function App(){const[step,setStep]=useState(0);const[style,setStyle]=useState(0);const[gender,setGender]=useState('men');const[paused,setPaused]=useState(false);const[voice,setVoice]=useState('idle');const[change,setChange]=useState(false);return <div className="app"><Header step={step} setStep={setStep}/>{step===0&&<Shell {...{step,setStep}} kicker="SMART HAIRCARE. REAL TECHNOLOGY." title="Your face. Your next style." desc="Clip-E connects computer vision, personalized haircut planning and a physical robotic arm—turning your goal into a reviewable, measurable cut plan before anything moves."><section className="hero"><div><div className="pill"><Sparkles size={16}/> SEE → UNDERSTAND → PLAN → VERIFY → MOVE → LEARN</div><h2>Personalized to you.<br/><em>Built to move.</em></h2><p>Explore styles, understand why they fit your goals, generate a spatial cut map, preview robotic motion and approve every step.</p><button className="primary big" onClick={()=>setStep(1)}>Start Your Journey <ArrowRight/></button><div className="features"><span><Camera/>Vision analysis</span><span><Target/>Cut mapping</span><span><ShieldCheck/>Human approval</span></div></div><div className="robotCard"><div className="techLabel">CLIP-E // PROTOTYPE DIGITAL TWIN</div><Arm/><div className="readout"><b>HOME POSITION</b><span>ESP32-S3 · Wi-Fi</span></div></div></section><section className="why"><article><b>01 / UNDERSTAND</b><h3>More than a recommendation.</h3><p>Face geometry, hair characteristics and your goals become inputs—not rules. You make the final style decision.</p></article><article><b>02 / TRANSLATE</b><h3>From style to cut map.</h3><p>The selected look becomes measurable zones, target lengths, blend regions and protected boundaries.</p></article><article><b>03 / VERIFY</b><h3>Movement you approve.</h3><p>Preview the plan, tool, path and safety state before sending structured instructions to Clip-E.</p></article></section></Shell>}
{step===1&&<Shell {...{step,setStep}} kicker="01 / SEE" title="Scan your face + hair" desc="Use the camera or upload a clear image. This prototype uses visual input to create a planning profile—not a beauty score."><div className="split"><div className="scanner"><div className="scanline"/><small>ALIGN FACE WITH GUIDE</small></div><div className="panel"><h3>Capture input</h3><button className="primary wide"><Camera/> Use Camera</button><button className="ghost wide"><Upload/> Upload Photo</button><hr/><h4>For a useful scan</h4><p>Face forward in even lighting. Keep the hairline visible and remove hats or anything covering the head shape.</p><div className="privacy"><ShieldCheck/> Camera input is used to build the session profile. This demo does not imply biometric identification.</div></div></div></Shell>}
{step===2&&<Shell {...{step,setStep}} kicker="02 / UNDERSTAND" title="Your analysis" desc="A planning profile combines visible geometry with the hair information you confirm."><div className="analysis"><div className="head"><ConceptHead hair="crop" technical className="analysisConcept"/><span>FACE GEOMETRY</span></div><div className="metrics">{[['Face shape','Oval / balanced'],['Hairline','Mapped'],['Current length','Short–medium'],['Distribution','Profile created'],['Goal compatibility','High']].map(x=><div><span>{x[0]}</span><b>{x[1]}</b></div>)}</div><div className="panel"><h3>Your hair profile</h3><p>Clip-E separates observed information from what you tell us. Confirm your goals before recommendations are generated.</p><label>Primary goal<select><option>Maintain my style</option><option>Grow it out</option><option>Manage length</option><option>Maintain my fade</option><option>Transition to a new style</option></select></label><label>Priority<select><option>Easy maintenance</option><option>More volume</option><option>Sharper structure</option></select></label></div></div></Shell>}
{step===3&&<Shell {...{step,setStep}} kicker="03 / SELECT" title="Haircuts mapped to your face shape" desc="A quick visual guide connects face geometry to haircut ideas. Use it as a starting point, then choose and customize what you actually want."><div className="faceCutGuide">
<div className="guideTop"><div><b>2-MINUTE STYLE MATCH</b><h2>Top haircut ideas</h2><p>Face shape → haircut options → your final choice</p></div><div className="guideKey"><span><i className="keyDot orange"/>Structure</span><span><i className="keyDot blue"/>Movement</span><span><i className="keyDot pale"/>Softness</span></div></div>
{[
['Round',[['Long Layers','adds length'],['Textured Pixie','adds height'],['Side Bangs','balances roundness']]],
['Oval',[['Sleek Bob','flatters symmetry'],['Wavy Shag','adds texture'],['Blunt Cut','highlights structure']]],
['Square',[['Long Layers','softens angles'],['Layered Bob','frames face'],['Wispy Bangs','blurs jawline']]],
['Heart',[['Chin-Length Bob','balances forehead'],['Side-Swept Pixie','draws focus to eyes'],['Soft Waves','adds volume to chin']]],
['Diamond',[['Layered Midi','flatters cheekbones'],['Bob with Fringe','widens forehead'],['Textured Crop','adds softness']]],
['Rectangle',[['Medium Curls','adds width'],['Layered Bob','breaks length'],['Side-Swept Fringe','shortens forehead']]]
].map((row,ri)=><section className={'shapeRow '+(ri===1?'profileMatch':'')}><div className="shapeName"><div className={'faceShape fs'+ri}/><b>{row[0]}</b>{ri===1&&<span>YOUR MATCH</span>}</div>{row[1].map((cut,ci)=><button className="cutIdea" onClick={()=>setStyle(ci)}><div className={'cutHead cut'+ri+'-'+ci}><span/></div><div><b>{cut[0]}</b><small>· {cut[1]}</small></div><ChevronRight/></button>)}</section>)}
</div><div className="guideNote"><Sparkles/><div><b>Recommendations, not rules.</b><p>Face shape is one input. Hair texture, density, maintenance goals and personal preference still shape the final Clip-E plan.</p></div></div></Shell>}
{step===4&&<Shell {...{step,setStep}} kicker="04 / CUSTOMIZE" title="Make the cut yours" desc="Choose a hairstyle, then tune the target before it becomes a robot plan."><div className="customStudio"><aside className="panel controls studioControls"><h3>Customize Your Cut</h3>{[['Top Length','25 mm'],['Side Length','6 mm'],['Fade Height','Mid'],['Texture','Medium']].map((x,i)=><label key={x[0]}>{x[0]} <b>{x[1]}</b><input type="range" defaultValue={[72,28,52,48][i]}/></label>)}<label>Finish<select><option>Natural</option><option>Defined</option><option>Soft transition</option></select></label><div className="studioToggles"><span>Preserve Top <i>ON</i></span><span>Blend Sides <i>ON</i></span><span>Enhance Texture <i>OFF</i></span></div></aside><section className="studioModel"><ConceptHead hair={['crop','fade','crew'][style%3]} view="quarter" className="heroMaleHead"/><div className="viewSwitch"><b>Front</b><b className="selectedView">Left</b><b>Right</b><b>Back</b></div></section><aside className="styleGallery"><div className="dashTitle"><div><h3>Choose a Style</h3><p>36 individual hairstyle slots</p></div><span>36 OPTIONS</span></div><div className="styleGender"><button className={gender==='men'?'active':''} onClick={()=>{setGender('men');setStyle(0)}}>MEN · 18</button><button className={gender==='women'?'active':''} onClick={()=>{setGender('women');setStyle(0)}}>WOMEN · 18</button></div><div className="hairSlots">{(gender==='men'?[
['Textured Crop',0],['Low Fade',1],['Mid Fade',2],['High Fade',3],['Buzz Cut',4],['Crew Cut',5],['Classic Taper',6],['Side Part',7],['Curly Top',8],['Waves',9],['French Crop',10],['Ivy League',11],['Messy Fringe',12],['Slick Back',13],['Undercut',14],['Bro Flow',15],['Middle Part',16],['Mullet',17]
]:[
['Long Layers',18],['Soft Waves',19],['Beach Waves',20],['Straight & Sleek',21],['Curtain Bangs',22],['Face Framing',23],['Butterfly Cut',24],['Wolf Cut',25],['Shag',26],['Blunt Cut',27],['Side Part Waves',28],['High Ponytail',29],['Low Bun',30],['Messy Bun',31],['Braided Style',32],['Half Up Half Down',33],['Claw Clip Updo',34],['Curly Long',35]
]).map((x,i)=><button key={x[1]} className={'hairSlot '+(i===style?'chosen':'')} onClick={()=>setStyle(i)}><span className="hairCrop" style={{'--slot':x[1]}}/><b>{x[0]}</b><small>{String(x[1]+1).padStart(2,'0')}</small></button>)}</div></aside></div></Shell>}
{step===5&&<Shell {...{step,setStep}} kicker="05 / PLAN" title="Your Cut Map" desc="Review the mapped cut depth, planned robot movement, tools and safety state before sending the plan to Clip-E."><div className="cutDash">
<section className="dashPanel cutMapPanel"><div className="dashTitle"><div><h3>Your Cut Map</h3><p>Mapped removal depth and protected regions.</p></div></div><div className="seg"><b>Cut Depth</b><span>Zones</span><span>Robot Path</span></div><div className="heads4">{['Front','Right','Back','Left'].map((v,i)=><div><ConceptHead view={['front','right','back','left'][i]} hair="crop" technical active className={'mapConcept view'+i}/><b>{v}</b></div>)}</div><div className="mapped"><b>Mapped Zones</b><span><i className="dot orange"/>Top (Medium)</span><span><i className="dot blue"/>Sides (Low)</span><span><i className="dot rust"/>Back (Medium)</span><span><i className="dot pale"/>Neckline (Detail)</span></div></section>
<section className="dashPanel robotSim"><div className="dashTitle"><div><h3>Robot Preview</h3><p>Preview Clip-E's planned movement.</p></div></div><div className="seg"><b>Arm Movement</b><span>Cut Sequence</span><span>Angles</span></div><div className="simBody"><ol>{['Top Pass','Right Side','Back','Left Side','Detail'].map((x,i)=><li><i>{i+1}</i><span><b>{x}</b><small>{['Trim and texture top','Fade and blend','Clean and blend','Fade and blend','Neckline and edges'][i]}</small></span></li>)}</ol><div className="simVisual"><ConceptHead view="quarter" hair="crop" technical active className="robotConcept"/><Arm mode="map"/><div className="motionline"/></div></div><div className="simProgress"><button>▶</button><span><i/></span><b>78%</b></div></section>
<aside className="dashPanel details"><div className="dashTitle"><h3>Cut Plan Details</h3><button className="ghost">Edit</button></div><div className="styleSummary"><div className="styleThumb"/><div><b>{styles[style][0]}</b><small>Modern · Versatile · Clean</small><p>{styles[style][1]}</p></div></div><h4>Cut Parameters</h4>{[['Top Length','12 mm',70],['Side Fade','3 mm',30],['Back Length','6 mm',62],['Neckline','1 mm',12]].map(x=><label>{x[0]}<input type="range" defaultValue={x[2]}/><b>{x[1]}</b></label>)}<h4>Tools & Settings</h4><div className="toolrow"><span>✂ Clipper<small>#1, #2, #3</small></span><span>⌁ Trimmer<small>Detail work</small></span><span>◷ Time<small>~12 min</small></span></div></aside>
<section className="dashPanel liveView"><div className="dashTitle"><div><h3>Live Robot View</h3><p>Monitor Clip-E as it executes the validated plan.</p></div><span className="live">● LIVE</span></div><div className="liveScene"><Arm mode="ready"/><div className="bench"/><span>PROTOTYPE CAMERA FEED</span></div></section>
<section className="dashPanel sendPanel"><div className="dashTitle"><div><h3>Send to Clip-E</h3><p>Your cut plan is ready for validation.</p></div></div><div className="sendGrid"><div>{[['Cut Plan Ready','All parameters set'],['Head Map Generated','3D model synced'],['Robot Connected','Clip-E is online'],['Safety Systems Active','Monitoring in real time']].map(x=><div className="readyRow"><CheckCircle2/><span><b>{x[0]}</b><small>{x[1]}</small></span><i>✓</i></div>)}<button className="primary wide"><Wifi/> Send to Clip-E <ArrowRight/></button></div><div className="transmit"><div className="cloud">⌁</div><div className="fileIcon">▤</div><ArrowRight/><Arm mode="ready"/><b>Transmit to Clip-E</b><small>Your style. Our precision.</small></div></div></section>
<aside className="dashPanel sysPanel"><h3>System Status</h3>{[['Clip-E Connected','Ready to receive cut plan'],['Camera Feed','Active'],['Robot Arm','Online'],['Sensors','Calibrated'],['Safety Check','Passed']].map((x,i)=><div className="sys"><i>{i===0?'◆':'✓'}</i><span><b>{x[0]}</b><small>{x[1]}</small></span></div>)}</aside>
</div></Shell>}
{step===6&&<Shell {...{step,setStep}} kicker="06 / VERIFY" title="Live Safety Monitoring" desc="Clip-E keeps monitoring position, clearance and session inputs after the initial scan. Visible facial cues are treated only as an additional signal—not as a definitive measure of how someone feels."><div className="safetyGrid">
<section className="dashPanel safetyVisual"><div className="dashTitle"><div><h3>Continuous Head Tracking</h3><p>3D position model + restrained camera overlay</p></div><span className="trackingBadge">● TRACKING ACTIVE</span></div><div className="safetyScene"><ConceptHead view="quarter" hair="crop" technical className="safetyConcept"/><Arm mode="ready"/><div className="clearanceRing"/><div className="zoneLabel">PLANNED CUTTING ZONE</div></div></section>
<aside className="dashPanel safetyStatus"><h3>Safety State</h3>{[['User Position','Stable','Head position remains within the planned cutting zone.'],['Movement Tracking','Active','Monitoring for unexpected head movement.'],['Face Monitoring','Active','Visible facial cues are an additional safety input.'],['Robot Clearance','Safe','Tool distance and operating area are monitored.'],['Emergency Stop','Ready','Manual pause and stop controls remain available.']].map((x,i)=><div className="safetyRow"><i className={i===4?'orangeState':''}>{i===4?'!':'✓'}</i><span><small>{x[0]}</small><b>{x[1]}</b><p>{x[2]}</p></span></div>)}</aside>
<section className="dashPanel cameraMonitor"><div className="dashTitle"><div><h3>Live Camera + Robot View</h3><p>Movement, tool clearance and current zone</p></div><span className="live">● LIVE</span></div><div className="monitorFeed"><ConceptHead view="quarter" hair="crop" technical className="monitorConcept"/><Arm mode="map"/><div className="safeBox"/><span>ZONE 02 · RIGHT SIDE</span></div></section>
<aside className="dashPanel stopPanel"><ShieldCheck/><h3>User control stays available.</h3><p>Tracking, sensors, communication and manual controls work together. Any unexpected movement can trigger a pause for review.</p><button className="pauseBtn" onClick={()=>setPaused(!paused)}><Pause/> {paused?'Resume Clip-E':'Pause Clip-E'}</button><button className="stopBtn"><Square/> Stop Cut</button><small>{paused?'ARM PAUSED · PLAN PRESERVED':'ARM READY · MANUAL STOP READY'}</small></aside>
</div></Shell>}
{step===7&&<Shell {...{step,setStep}} kicker="07 / MOVE" title="Live Cut" desc="One workspace for the current robot task, mapped cutting zone, progress, voice communication and safety controls."><div className="liveCutGrid">
<section className="dashPanel liveHero"><div className="dashTitle"><div><h3>Clip-E Session</h3><p>Current task · Right side blend</p></div><span className={paused?'pausedBadge':'trackingBadge'}>{paused?'● PAUSED':'● CUT IN PROGRESS'}</span></div><div className="liveHeroScene"><ConceptHead view="right" hair="crop" technical active className="activeConcept"/><Arm mode={paused?'home':'map'}/><div className="cutArc"/></div><div className="taskBar"><span><small>CURRENT TASK</small><b>Right Side · Fade + Blend</b></span><span><small>TARGET</small><b>4 mm</b></span><span><small>PROGRESS</small><b>62%</b></span></div><div className="progressTrack"><i/></div></section>
<aside className="dashPanel sessionSafety"><h3>Safety</h3>{[['Position','Stable'],['Movement','Active'],['Clearance','Safe'],['Camera','Active']].map(x=><div className="miniStatus"><CheckCircle2/><span>{x[0]}</span><b>{x[1]}</b></div>)}<button className="pauseBtn" onClick={()=>setPaused(!paused)}><Pause/> {paused?'Resume Clip-E':'Pause Clip-E'}</button><button className="stopBtn"><Square/> Stop Cut</button></aside>
<section className="dashPanel voicePanel"><div className="dashTitle"><div><h3>Talk to Clip-E</h3><p>Voice control with confirmation for plan changes.</p></div><Mic/></div><button className={'micOrb '+(voice==='listening'?'listening':'')} onClick={()=>setVoice(voice==='listening'?'idle':'listening')}><Mic/><span>{voice==='listening'?'Clip-E Listening':'Start Voice'}</span></button><div className="voiceTranscript"><MessageCircle/><div><small>YOU</small><b>“Make the sides a little shorter.”</b></div></div><div className="changeCard"><span>CHANGE DETECTED · SIDE LENGTH</span><div><p>Current<b>6 mm</b></p><ArrowRight/><p>Requested<b>4 mm</b></p></div>{!change?<button className="primary wide" onClick={()=>setChange(true)}>Confirm change</button>:<div className="confirmed"><CheckCircle2/> Change confirmed · plan will update before motion resumes.</div>}</div><div className="quickCommands">{['Pause','How much longer?','What are you cutting?','Leave the top longer','Show me the back','Original cut'].map(x=><button onClick={()=>setVoice('listening')}>{x}</button>)}</div></section>
<section className="dashPanel clipSpeaks"><div className="dashTitle"><h3>Clip-E Communication</h3><Volume2/></div>{['I’m starting the right side.','Please keep your head still for a moment.','The right side is complete.','I detected movement, so I paused the arm.'].map((x,i)=><div className={'speech '+(i===0?'current':'')}><Volume2/><span>{x}</span></div>)}</section>
<section className="dashPanel liveCamera"><div className="dashTitle"><div><h3>Camera Feed</h3><p>Live spatial monitoring</p></div><span className="live">● LIVE</span></div><div className="monitorFeed bigFeed"><div className="monitorHead"/><Arm mode="ready"/><div className="safeBox"/></div></section>
</div></Shell>}
{step===8&&<Shell {...{step,setStep}} kicker="08 / LEARN" title="Your Hair Journey" desc="Turn one session into useful context for the next—your preferences, goals and cut history in one place."><div className="journey"><div className="panel passport"><h3>Hair Passport</h3><div className="avatar">SK</div><b>Current direction</b><h2>{styles[style][0]}</h2><div className="tags"><span>Easy maintenance</span><span>Natural blend</span><span>12 mm top</span></div></div><div className="timeline"><article><i/><b>TODAY</b><h3>Clip-E plan created</h3><p>Your target lengths, cut map and preferences are ready to reference next time.</p></article><article><i/><b>NEXT STEP</b><h3>Maintain the shape</h3><p>Track growth and compare your next scan against this target rather than starting over.</p></article><article><i/><b>TIP FOR YOUR GOAL</b><h3>Protect your target length</h3><p>For maintenance, prioritize consistent target zones over removing the maximum amount each session.</p></article></div></div><section className="future"><h2>One platform. Different people. Different hair.</h2><p>Clip-E is being designed as a modular hair robotics platform. Broader textures, lengths and needs may require different sensing, positioning, motion strategies and tools—not one universal cutting method.</p><div>{['PRECISION CLIPPER','ADJUSTABLE GUARD','COMB / SECTIONING','TENSION CONTROL','TEXTURE-SPECIFIC TOOLS'].map(x=><span>{x}</span>)}</div></section></Shell>}
{step===9&&<Shell {...{step,setStep}} kicker="ACCESSIBILITY + APPLICATIONS" title="Why Clip-E matters" desc="Clip-E is being designed to explore how robotics could make personal grooming more adaptable, repeatable and accessible. These are intended applications—not claims that the current prototype addresses every person, disability or environment."><div className="accessIntro"><div><Accessibility/><h2>Personal technology should adapt to the person.</h2><p>The same system that maps a haircut can support multiple ways to set preferences, confirm changes, monitor a session and preserve a repeatable grooming plan.</p></div><div className="accessHead"><ConceptHead view="quarter" hair="crop" technical className="accessConcept"/><Arm mode="ready"/></div></div><div className="applicationGrid">{[
['Independent Grooming','A potential future tool for people who face physical barriers to independently cutting or maintaining their hair.','01'],
['Limited Hand or Arm Mobility','Automated positioning and cutting could reduce reliance on the fine hand movements required by traditional grooming tools.','02'],
['Communication Support','Visual controls, voice interaction and explicit confirmations provide multiple ways to communicate preferences.','03'],
['Consistent Maintenance Cuts','A saved haircut profile could help recreate the same dimensions and style during future sessions.','04'],
['Remote or Limited-Service Environments','Future versions could provide standardized grooming options where professional services are difficult to access.','05'],
['Personalized Hair Care','Users could track haircut history, goals, preferred lengths and style changes over time.','06']
].map(x=><article><span>{x[2]}</span><h3>{x[0]}</h3><p>{x[1]}</p><ArrowRight/></article>)}</div><div className="designPrinciple"><ShieldCheck/><div><b>DESIGNED TO EXPLORE, NOT OVERCLAIM</b><p>Accessibility needs vary widely. Clip-E’s future development would require testing with users, adaptable controls, different tools and sensing strategies, and appropriate safety validation for each intended use.</p></div></div></Shell>}
</div>}createRoot(document.getElementById('root')).render(<App/>);